### ISSUE TITLE
"No space left on device" bug

### ISSUE THREAD

**Issue by ppuliu** [quwubin/MFEprimer#3]
When the user doesn't have root access, all the functions using "/temp" directory will cause "No space left on device" error. I think it's better to change the default "parent_dir" in "chilli.session" function as the user output directory.

**Comment by quwubin** [comment]
It 's "/tmp" in chilli.session. And the directory "/tmp" is writable for all users in linux system.
Which system do you use? Please check the disk usage of your system.

**Comment by ppuliu** [comment]
Hi,

You are right. It is indeed writable. Thanks.


--

*PhD Student*
*Department of Computer Science*
*University of California, Santa Barbara*

*www.cs.ucsb.edu/~honglei/ <http://www.cs.ucsb.edu/~honglei/>*
