### ISSUE TITLE
What's the meaning of negative PPC values

### ISSUE THREAD

**Issue by billzt** [quwubin/MFEprimer#4]
Sometimes I found negative PPC values. They always appear on Seq1xSeq1 or Seq2xSeq2 combinations (that is, FF or RR instead of normal FR combination). But I don't know why this could lead to negative PPC values.

**Comment by quwubin** [comment]
The negative PPC values mean that these amplicons are produced by one
primer self. I marked by negative value for alert.


Wubin Qu

Email:   quwubin@gmail.com
Scholar: *http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en
<http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en>*

**Comment by billzt** [comment]
Thanks. Then I suggest writing this to the wiki.

Currently, all the negative PPC values I've ever seen are very small (just around 30% or so). I'm not sure whether PPC values such as -100% could appear and infulence the real experiments

**Comment by quwubin** [comment]
OK. Thanks for the suggestion.

Just ignore the negative sign, and treat them as normal 100%. Then analysis
the potential amplicons whether they affect your experiments.

By the way, I wrote a protocol for how to choosing specific primers with
MFEprimer, if interested, please download it here:
http://quwubin.cn/download/QuWB_2015_MFEprimer_Protocol.pdf


Wubin Qu

Email:   quwubin@gmail.com
Scholar: *http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en
<http://scholar.google.com/citations?user=Ayyglz8AAAAJ&hl=en>*
