### ISSUE TITLE
Some missing prerequisites to install MFEprimer server?

### ISSUE THREAD

**Issue by billzt** [quwubin/MFEprimer#6]
I don't know why, but when I intall a local mirror of MFEprimer-2.0 webserver in a new machine, after I follow https://github.com/quwubin/MFEprimer#create-a-local-mirror-of-mfeprimer-20 and installed Python (>= 2.7), psutil and Flask, it still encounter error:

```
$ ./MFEprimerWeb.py
Traceback (most recent call last):
  File "./MFEprimerWeb.py", line 25, in <module>
    from chilli import ve
  File "/var/www/cgi-bin/MFEprimerWeb-master/chilli/ve.py", line 12, in <module>
    import cairo
ImportError: No module named cairo
```

First I try to install `pip install pycairo`, however it has been removed from the pypi, then I have to `pip install cairocffi`, and then **edit MFEprimerWeb-master/chilli/ve.py: change `import cairo` to `import cairocffi as cairo`**

After that, it still encounter error:
```
$ ./MFEprimerWeb.py
Traceback (most recent call last):
  File "./MFEprimerWeb.py", line 35, in <module>
    from cron import get_blog_news
  File "/var/www/cgi-bin/MFEprimerWeb-master/cron/get_blog_news.py", line 6, in <module>
    import pytumblr
ImportError: No module named pytumblr
```

What should I do is: `pip install pytumblr`

Then it is OK

**Comment by quwubin** [comment]
Thanks for finding the solution. 

It looks like that the manual should be updated to adjust the change of package of "cairo".

Thanks again.
