### ISSUE TITLE
Some strang JS errors in MFEPrimerWeb

### ISSUE THREAD

**Issue by billzt** [quwubin/MFEprimer#7]
I don't know how these errors come out. Several months later all are OK. However recently there are some JS errors.

(1) click " Example" in "Enter the primer sequences" leads to a JS error:
```
TypeError: who is null   function.js:417:9
```

(2) select the background database leads to a JS error:
```
ReferenceError: db_selected_changed is not defined
```

**Comment by quwubin** [comment]
These JS code are very simple in "function.js" file. May the browser actives some safe control and
please try another browser and test.
